import Head from "next/head";
import LoginPage from "./login";
import PlayPage from "./dashboard/play";
import userStore from "@/stores/userStore";
import { Box } from "@chakra-ui/react";

export default function Home() {
  const {
    loggedIn,
    // username,
    // loginType,
    // solana_wallet_address,
    // userProfilePic,
  } = userStore();

  return (
    <>
      <Head>
        <title>LIBERTÉ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box minHeight="100vh" bg="black" color="white" fontFamily="Montserrat">
        {loggedIn ? <PlayPage /> : <LoginPage />}
      </Box>
    </>
  );
}
