import { useEffect } from "react";
import Head from "next/head";
import userStore from "@/stores/userStore";
import { Box } from "@chakra-ui/react";
import theme from "@/styles/theme";
import { useRouter } from "next/router";
import LoginPage from "./login";
import toast from "react-hot-toast";

export default function Home() {
  const { loggedIn, solana_wallet_address } = userStore();
  const router = useRouter();

  useEffect(() => {
    if (loggedIn && solana_wallet_address.trim() != "") {
      router.push("/play");
      toast.success("Logged in");
    }
  }, [loggedIn, router, solana_wallet_address]);

  return (
    <Box>
      <Head>
        <title>LIBERTÉ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        minHeight="100vh"
        bg={theme.colors.background}
        color="white"
        fontFamily="Montserrat"
      >
        <LoginPage />
      </Box>
    </Box>
  );
}
