import { useEffect } from "react";
import Head from "next/head";
import userStore from "@/stores/userStore";
import { Box } from "@chakra-ui/react";
import theme from "@/styles/theme";
import { useRouter } from "next/router";
import toast from "react-hot-toast";
import HelloWorld from "@/components/HelloWorld";
import PlayPage from "./play";

export default function Home() {
  const { loggedIn, wallet_address } = userStore();
  const router = useRouter();

  useEffect(() => {
    if (!loggedIn || wallet_address.trim() === "") {
      router.push("/login");
    } else {
      toast.success("Logged in");
    }
  }, [loggedIn, router, wallet_address]);

  return (
    <Box>
      <Head>
        <title>ILLUMINATED</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        minHeight="100vh"
        bg={theme.colors.background}
        color="white"
        fontFamily="Montserrat"
      >
        {/* <div>
        <h1>Hello from Next.js</h1>
        <HelloWorld />
      </div> */}
        <PlayPage />
      </Box>
    </Box>
  );
}
